####################################################################
# ansible_ssh_user: root
####################################################################
# 下载软件包存放目录
files: /mnt/d/box/ansible/files
####################################################################
# rsync 源目录
src_file: /mnt/d/box/ansible
# rsync 目标目录
dest_file: /tmp/
####################################################################
# CPU架构
arch: x86_64
# arch: s390x
####################################################################
# nginx 版本
nginx_version: 1.22.0
# docker 版本
# docker版本大于18.06.3时，-ce省略，如20.10.9
docker_version: 18.06.3-ce
####################################################################
# keepalived 设置VIP地址
VIP_ADDRESS_1: 192.168.10.233
# keepalived 设置VIP网口名称
NIC: eth0
# keepalived 配置主从密码，可使用openssl rand -hex 4生成
KEEPALIVED_PASS: 4d20e81d
# 虚拟路由ID
VRID: 51
MASTER_IP: "192.168.10.88"
BACKUP_IP: "192.168.10.89"
####################################################################
# haproxy 状态页配置IP
HA_VIP: "192.168.10.233"
# web 后端名称 IP地址 端口号
WEB1: { HOST: web1, IP: 192.168.10.88, PORT: 80 }
WEB2: { HOST: web2, IP: 192.168.10.89, PORT: 8080 }
####################################################################
