####################################################################
# ansible_ssh_user: root
####################################################################
# 下载软件包存放目录
files: /mnt/d/box/ansible/files
####################################################################
# rsync 源目录
src_file: /mnt/d/box/ansible
# rsync 目标目录
dest_file: /tmp/
####################################################################
# CPU架构
arch: x86_64
####################################################################
# nginx 版本
nginx_version: 1.22.0
# docker 版本
docker_version: 18.06.3
####################################################################