# etcd 集群间通信的IP和端口, 根据etcd组成员自动生成
# TMP_NODES=etcd-192.168.10.88=https://192.168.10.88:2380,
TMP_NODES: "{% for h in groups['etcd'] %}etcd-{{ h }}=https://{{ h }}:2380,{% endfor %}"
# 去掉最后的,
ETCD_NODES: "{{ TMP_NODES.rstrip(',') }}"

# etcd 集群初始状态 new/existing
CLUSTER_STATE: "new"