- name: docker check package
  shell: "[ -f {{ files }}/bin/docker ]"
  register: check_docker
  ignore_errors: true
  changed_when: false
  run_once: true
  connection: local

- block:
    - name: download docker package1
      get_url:
        url: "https://final233.ga/d/aliyun/bin/docker-{{ docker_version }}.tgz"
        dest: "{{ files }}/package/docker-{{ docker_version }}.tgz"
        validate_certs: no
        mode: 0644
      when: docker_version == "18.06.3-ce"
    
    - name: download docker package2
      get_url:
        url: "https://download.docker.com/linux/static/stable/{{ ARCH }}/docker-{{ docker_version }}.tgz"
        dest: "{{ files }}/package/docker-{{ docker_version }}.tgz"
        validate_certs: no
        mode: 0644
      when: docker_version != "18.06.3-ce"

    - name: 本地提取docker二进制文件
      unarchive:
        src: "{{ files }}/package/docker-{{ docker_version }}.tgz"
        dest: "{{ files }}/bin/"
        remote_src: yes
        extra_opts:
          - --strip-components=1
  connection: local
  run_once: true
  when: check_docker.rc != 0
