- name: 准备 ingress的部署文件
  template: src=ingress/ingress-nginx/{{ item }}.j2 dest={{ cluster_dir }}/yml/{{ item }}
  with_items:
    - "ingress-nginx.yaml"
  run_once: true
  connection: local

- name: 创建 ingress部署
  shell: "{{ cluster_dir }}/bin/kubectl apply -f {{ cluster_dir }}/yml/ingress-nginx.yaml"
  run_once: true
  connection: local