- name: 修改启动参数
  replace: 
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=.* rhgb quiet).*'
    replace: '\1 {{ cmdline }}"'
    backup: yes
  notify: 生成grub引导文件
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"