- name: 禁用GSSAPIAuthentication
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^(GSSAPIAuthentication).*'
    replace: '\1 no'
  notify: restart sshd

- name: 禁用sshd服务名称解析
  replace: 
    path: /etc/ssh/sshd_config
    regexp: '^(UseDNS).*'
    replace: '\1 no'