- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
    - "{{ cluster_dir }}/ssl"
    - "{{ cluster_dir }}/backup"
    - "{{ cluster_dir }}/yml"
    - "{{ cluster_dir }}/bin"
    - "{{ cluster_dir }}/user"
    - "~/.kube"

# 注册变量p，根据p的stat信息判断是否已经生成过ca证书，如果没有，下一步生成证书
# 如果已经有ca证书，为了保证整个安装的幂等性，跳过证书生成的步骤
- name: 读取ca证书stat信息
  stat: path="{{ cluster_dir }}/ssl/ca.pem"
  register: p

- name: 准备CA配置文件和签名请求
  template: src={{ item }}.j2 dest={{ cluster_dir }}/ssl/{{ item }}
  with_items:
    - "ca-config.json"
    - "ca-csr.json"
  when: p.stat.isreg is not defined

- name: 生成 CA 证书和私钥
  when: p.stat.isreg is not defined
  shell: "cd {{ cluster_dir }}/ssl && \
    {{ base_dir }}/bin/cfssl gencert -initca ca-csr.json | {{ base_dir }}/bin/cfssljson -bare ca -"
