- name: 执行脚本生成文件
  command: /home/tdgw/scripts/mod_time.sh hosts

# - name: 获取远程主机文件
  # fetch: src=/home/tdgw/scripts/run.sh dest=/tmp/

# - name: 下发run.sh至远程主机
#   copy: src=/tmp/{{ ansible_eth0.ipv4.address }}/home/tdgw/scripts/run.sh dest=/home/tdgw/scripts/ mode=0755 owner=tdgw

- name: 执行远程主机脚本
  command: /home/tdgw/scripts/run.sh

