- hosts:
    - localhost
  remote_user: root
  gather_facts: false
  roles:
    - kube-download
    - kube-ca
    - kube-config

- hosts:
    - kube-master
    - kube-node
    - etcd
  remote_user: root
  roles:
    - kube-pre
