- hosts:
    - kube_master
  remote_user: root
  # gather_facts: no
  roles:
    - kube-lb
    - kube-master
    - kube-node
  tasks:
    - name: Making master nodes SchedulingDisabled
      shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }} "
      when: "inventory_hostname not in groups['kube_node']"
      ignore_errors: true

    - name: Setting master role name
      shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
      ignore_errors: true
