# to install network plugin, only one can be choosen 
- hosts:
  - kube_master
  - kube_node
  remote_user: root
  roles:
  - cni
  # - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
