# Note: this playbook cann't run independently

- hosts: "{{ NODE_TO_ADD }}"
  remote_user: root
  roles:
    - kube-pre
    - { role: docker, when: "CONTAINER_RUNTIME == 'docker'" }
    # - { role: containerd, when: "CONTAINER_RUNTIME == 'containerd'" }
    - kube-lb
    - kube-master
    - kube-node
    # - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
  #
  tasks:
    - name: Making master nodes SchedulingDisabled
      shell: "{{ bin_dir }}/kubectl cordon {{ NODE_TO_ADD }} "
      when: "inventory_hostname not in groups['kube_node']"
      ignore_errors: true

    - name: Setting master role name
      shell: "{{ bin_dir }}/kubectl label node {{ NODE_TO_ADD }} kubernetes.io/role=master --overwrite"
      ignore_errors: true
