# 引用两个角色
- hosts: web
  remote_user: root
  # 为角色添加标签
  # 如何执行某个标签 ansible-playbook nginx+httpd_role.yml -t nginx
  roles:
    - { role: httpd, tags: ["web", "httpd"] }
    # 当操作系统版本为7才执行
    - {
        role: nginx,
        tags: ["web", "nginx"],
        when: ansible_distribution_major_version == "7"
      }
