app_dir: /apps/nginx
user_name: nginx
user_uid: 2000
group_name: nginx
group_gid: 2000
service_name: nginx
make_opt: "./configure --prefix={{ app_dir }}-{{ nginx_version }} \
  --with-http_ssl_module \
  --with-http_v2_module \
  --with-http_realip_module \
  --with-http_stub_status_module \
  --with-http_gzip_static_module \
  --with-pcre \
  --with-stream \
  --with-stream_ssl_module \
  --with-stream_realip_module"